# -*- coding: utf-8 -*-
"""Brent/Gasoil LR and Copula

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tZWN3PEDd8mRX8HfNHkXnfRlAe8NQwKp
"""

import eikon as ek
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import QuantileTransformer
from scipy.stats import norm, kendalltau

# 🔑 Eikon API Key
ek.set_app_key("7124cc602cee484ab6297f9468d491c9f585afdd")

# --------------------------------
# 1. Data Fetch (DAILY)
# --------------------------------
def get_daily(symbol, start, end):
    df = ek.get_timeseries(symbol,
        start_date=start.strftime('%Y-%m-%d'),
        end_date=end.strftime('%Y-%m-%d'),
        interval='daily',
        fields='CLOSE')
    return df.rename(columns={'CLOSE': symbol})

def fetch_daily(symbol):
    end = datetime.now()
    start = end - timedelta(days=365 * 2)  # 2 years
    return get_daily(symbol, start, end)

df1 = fetch_daily('LCOc1')
df2 = fetch_daily('LGOc1')
data = pd.concat([df1, df2], axis=1).dropna()

# --------------------------------
# 2. Preprocess
# --------------------------------
returns = np.log(data / data.shift(1)).dropna()

# --------------------------------
# 3A. Linear Regression Signal
# --------------------------------
def lr_signals(returns, window=60):
    beta = returns['LCOc1'].rolling(window).corr(returns['LGOc1']) * \
           (returns['LCOc1'].rolling(window).std() / returns['LGOc1'].rolling(window).std())
    spread = returns['LCOc1'] - beta * returns['LGOc1']
    z = (spread - spread.rolling(window).mean()) / spread.rolling(window).std()
    return z

# --------------------------------
# 3B. Gaussian Copula Signal
# --------------------------------
def copula_signals(returns, window=60):
    signals = pd.Series(index=returns.index, dtype=float)
    for end_ix in range(window, len(returns)):
        slice_r = returns.iloc[end_ix - window:end_ix]
        if slice_r.isnull().values.any():
            continue
        try:
            qt = QuantileTransformer(output_distribution='uniform', n_quantiles=min(100, len(slice_r)))
            u_v = qt.fit_transform(slice_r)
            tau, _ = kendalltau(u_v[:, 0], u_v[:, 1])
            if not np.isfinite(tau): continue
            rho = np.sin(np.pi / 2 * tau)
            if abs(rho) >= 0.999: continue
            z_u, z_v = norm.ppf(u_v[-1, 0]), norm.ppf(u_v[-1, 1])
            if not np.all(np.isfinite([z_u, z_v])): continue
            z = (z_u - rho * z_v) / np.sqrt(1 - rho ** 2)
            if np.isfinite(z):
                signals.iloc[end_ix] = z
        except Exception:
            continue
    return signals

# --------------------------------
# 4. Position Logic
# --------------------------------
def generate_positions(z, entry=1, exit=0.2):
    pos = 0
    pos_list = []
    for val in z:
        if pd.isna(val):
            pos_list.append(pos)
            continue
        if val > entry:
            pos = -1
        elif val < -entry:
            pos = 1
        elif abs(val) < exit:
            pos = 0
        pos_list.append(pos)
    return pd.Series(pos_list, index=z.index)

# --------------------------------
# 5. Run Strategies
# --------------------------------
z_lr = lr_signals(returns)
z_cp = copula_signals(returns)

pos_lr = generate_positions(z_lr)
pos_cp = generate_positions(z_cp)

spread = returns['LCOc1'] - returns['LGOc1']
ret_lr = pos_lr.shift(1) * spread
ret_cp = pos_cp.shift(1) * spread

perf = pd.DataFrame({
    'Linear Regression': ret_lr.cumsum(),
    'Copula': ret_cp.cumsum()
})

# --------------------------------
# 6. Evaluation
# --------------------------------
def evaluate_performance(returns, name):
    ret = returns.dropna()
    total_ret = ret.sum()
    sharpe = np.sqrt(252) * ret.mean() / ret.std()  # Daily Sharpe
    trades = (ret != 0).sum()
    win_rate = (ret > 0).sum() / trades if trades > 0 else np.nan
    print(f"🔍 {name} Strategy:")
    print(f"  ➤ Total Return: {total_ret:.4f}")
    print(f"  ➤ Sharpe Ratio: {sharpe:.2f}")
    print(f"  ➤ Win Rate: {win_rate:.2%}")
    print(f"  ➤ Trades: {trades}")
    print("-" * 40)

evaluate_performance(ret_lr, "Linear Regression")
evaluate_performance(ret_cp, "Copula")

# --------------------------------
# 7. Plot Results
# --------------------------------
plt.figure(figsize=(12, 6))
plt.plot(perf['Linear Regression'], label='Linear Regression')
plt.plot(perf['Copula'], label='Gaussian Copula')
plt.title("Daily Pair Trading Backtest: LCOc1 vs LGOc1")
plt.xlabel("Date")
plt.ylabel("Cumulative Return")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()